// V1.2 copy transcribed from 2029 Goobers.docx. Preserve intentional wording.
export const COPY = {
  errors: {
    name: "Use 1–14 characters.",
    caption: "Use 3–100 characters.",
    settings: "Choose 1–15 rounds and 10–60 captioning seconds.",
    full: "ROOM FULL",
    duplicateName: "NAME ALREADY IN USE, PICK ANOTHER",
    nameLocked: "Names can only change in the lobby.",
    color: "Choose a color, judgment-free.",
    kick: "Only the host can remove players in the lobby.",
    settingsHost: "Only the host can change lobby settings.",
    host: "HOST ONLY",
    phase: "PHASE ALREADY CLOSED",
    wait: "Action unavailable in this phase.",
    minimum: "4 PLAYERS REQUIRED",
    images: "Add images before starting.",
    finish: "Finish the game first. Monkey.",
    alive: "Ending early is unavailable.",
    skip: "No phase to skip.",
    breathe: "Please wait, don’t be that guy.",
    image: "Image unavailable.",
    pending: "JOINING NEXT ROUND",
    captionClosed: "CAPTION TIME ENDED",
    votingClosed: "VOTING CLOSED",
    selfVote: "You cannot vote for yourself, selfish little bastard.",
    unknown: "Action unavailable.",
    origin: "Please use this site. Please.",
    large: "Request too large.",
    create: "Could not create room. Try again.",
    session: "SESSION ENDED. Join again.",
    duplicateSession: "SESSION ALREADY OPEN",
    invalid: "Invalid request. Try again.",
    service: "CONNECTION LOST. Try again.",
    setup: "Room service needs setup. See README.",
    notFound: "ROOM NOT FOUND",
    offline: "CONNECTION LOST. Reconnecting…",
    busy: "Room busy. Try again.",
    deckHost: "Only the host can edit the deck in the lobby.",
    deckInvalid: "Choose images from the available library.",
    emptyDeck: "Select at least one image before starting.",
  },
  home: {
    eyebrow: "A MULTIPLAYER MAKE-FUN-OF-IT GAME",
    title1: "MAKE YOUR",
    title2: "FRIENDS",
    title3: "LAUGH.",
    title4: "",
    intro1: "Create a room. Ship out the code.",
    intro2: "Write captions and vote for your favorites.",
    players: "4–12 PLAYERS",
    downloads: "NO DOWNLOADS",
    tag: "PLAY TOGETHER",
    entryTop: "2029 GOOBERS",
    sticker1: "CAPTION",
    sticker2: "& VOTE",
    entry1: "HOP ON.",
    entry2: "",
    name: "YOUR NAME",
    namePlaceholder: "Enter your name",
    nameHint: "Up to 14 characters, emoji supported.",
    create: "CREATE A ROOM",
    or: "OR JOIN A ROOM",
    code: "ROOM CODE",
    join: "JOIN →",
    note: "Join with a room code sent by the host.",
    marquee: "WRITE A CAPTION ✳ WATCH THE SLIDESHOW ✳ VOTE FOR YOUR FAVORITE ✳",
    footer1: "A GAME FOR FRIENDS.",
    footer2: "2029 GOOBERS",
  },
  lobby: {
    title: "LOBBY",
    invite: "INVITE YOUR FRIENDS",
    assemble: "MEET THE",
    goobers: "GOOBERS.",
    codeLabel: "ROOM CODE",
    copy: "COPY CODE ↗",
    you: "YOU",
    offline: "OFFLINE",
    online: "CONNECTED",
    needed: "More players needed; the more the merrier",
    rename: "RENAME",
    rounds: "ROUNDS",
    timer: "CAPTION TIMER",
    mode: "IMAGE MODE",
    same: "SAME IMAGE",
    different: "DIFFERENT IMAGES",
    start: "START GAME ↗",
    hint: "Click your tag to change your name or color.",
    joining: "YOU’RE IN",
    joiningHint: "JOINING NEXT ROUND",
    waiting: "Waiting for [HOST] to start…",
  },
  caption: {
    counter: "[X] / [MAX]",
    submitted: "· [SUBMITTED]/[ELIGIBLE] SUBMITTED",
    title: "WRITE A",
    titleAccent: "CAPTION.",
    label: "Your caption",
    placeholder: "Write your caption…",
    update: "UPDATE CAPTION ↗",
    submit: "SUBMIT CAPTION ↗",
    saved: "Submitted. You can edit until captioning closes.",
  },
  round: {
    starting: "GET READY",
    loading: "STARTING GAME",
    intro: "NEW ROUND",
    final: "FINAL",
    round: "ROUND",
    roundEnd: "ROUND",
    seconds: "SECONDS",
  },
  shame: {
    title: "PIN OF SHAME",
    subtitle: [
      "This dude couldn’t think of a sentence.",
      "They forgot to press the “submit” button 💀",
      "AFK?",
      "You have permission to yell at them",
      "They haven’t understood the concept of a keyboard",
      "Too creative for ts",
      "Skill issue",
    ],
  },
  grave: {
    title: "R.I.P",
    subtitle: [
      "Disconnected before submitting.",
      "Shot 13 times",
      "Here lies disconnected user… how unfortunate",
      "Verity took them",
      "NO NO NO NO! COME BACK!!",
      "Someone oughta bring them back",
      "Kill issue",
    ],
  },
  slideshow: {
    exhibit: "MEME",
    anonymous: "ANONYMOUS",
    vote: "TIME TO DECIDE…",
    next: "NEXT UP…!",
    waiting: "Waiting for [HOST] to continue.",
    waitingEnd: "to continue.",
  },
  voting: {
    intro: "ONE VOTE PER PLAYER",
    title: "TIME TO",
    accent: "VOTE.",
    own: "YOUR JOKE",
    selected: "✓ SELECTED",
    select: "SELECT",
    hint: "Change your vote until voting closes. Missed votes are randomized. Don’t complain.",
  },
  results: {
    intro: "VOTING COMPLETE",
    verdict: "VOTE RESULTS…",
    empty: "No captions submitted. No points awarded. Skill issue.",
    single: "Only one caption submitted. They get all the money 🤑",
    tie: "TIED WINNERS",
    winnerIntro: "RESULTS",
    winner: ["ROUND WINNER", "WOOHOOOO", "WINNER WINNER CHICKEN DINNER"],
    noWinner: ["NO WINNER", "Y'ALL SUCK, NO WINNERS", "NO ONE WON, LOCK IN"],
    unanimous: [
      "✳ UNANIMOUS +50%",
      "✳ EVERYONE LOVED IT +50%",
      "✳ FAN FAVORITE +50%",
    ],
    authorTitle: "CAPTION AUTHORS",
    points: "+[X] POINTS",
    streak: "🔥 STREAK ×[X] · +10%",
    votes: "[X] votes",
  },
  leaderboard: {
    intro: "ROUND COMPLETE",
    title: "CURRENT",
    accent: "STANDINGS",
    consolation: "Last place",
    next: "NEXT ROUND",
    final: "FINAL RESULTS",
    waiting: "Waiting for [HOST].",
    you: "(you)",
    streak: "🔥 STREAK ×[X]",
  },
  podium: {
    intro: "GAME COMPLETE",
    title: "FINAL",
    accent: "PODIUM",
    tied: "TIED",
    first: "1ST",
    second: "2ND",
    third: "3RD",
  },
  awards: {
    intro: "GAME AWARDS",
    title: "PLAYER",
    accent: "AWARDS",
    best: "🏆 BEST MEME · [X] VOTES",
    pins: "📌 Pin Collector",
    fire: "🔥 On Fire",
    votes: "💖 People Pleaser",
    deaths: "🪦 Gone Too Soon",
    robbed: "😭 Robbed",
    continue: "CONTINUE →",
  },
  end: {
    intro: ["GAME OVER", "ALL DONE", "PACK IT UP"],
    title: "GO FOR",
    accent: "ANOTHER?",
    rematch: "REMATCH ↗",
    lobby: "RETURN TO LOBBY",
    waiting: "Waiting for the host.",
  },
  common: {
    reconnecting: "Reconnecting…",
    lost: "CONNECTION LOST",
    recover: "Trying to reconnect…",
    retry: "RETRY",
    retrySession: "RECONNECT",
    leaveSession: "LEAVE SESSION",
    vanished: "HALF THE PLAYERS DISCONNECTED, HAH!",
    continue: "CONTINUE GAME",
    end: "END GAME",
    leave: "LEAVE ROOM",
    skip: "SKIP PHASE ↗",
    footer: "2029 GOOBERS",
    fallback: "IMAGE UNAVAILABLE",
    fallbackHint: "You can still submit a caption.",
    helpTitle: "HOW TO PLAY",
    help: "Write a caption, watch the slideshow, then vote.",
    scoring:
      "Each vote earns 25 points. Every other eligible player’s manual vote earns +50%. Consecutive wins add +10%.",
  },
  site: {
    tagline: "terrible captions, but fun as hell.",
    description: "A private meme-caption party for you and your friends.",
  },
  tie: {
    title: "TIE",
    subtitle: "TIED WINNERS",
  },
  themes: {
    label: "Theme",
    original: "Original",
    light: "Light",
    dark: "Dark",
    coffee: "Coffee",
    vibrant: "Vibrant",
  },
  deck: {
    title: "GAME DECK",
    edit: "EDIT DECK",
    close: "CLOSE DECK",
    all: "USE ALL",
    blacklist: "BLACKLIST",
    whitelist: "WHITELIST",
    selectAll: "SELECT ALL",
    clear: "CLEAR SELECTION",
    summary: "[ACTIVE] / [TOTAL] IMAGES ACTIVE",
    repeat: "This deck may repeat images during the game.",
    enabled: "ENABLED",
    disabled: "DISABLED",
    selected: "SELECTED",
    excluded: "EXCLUDED",
    page: "PAGE [PAGE] / [TOTAL]",
    next: "NEXT",
    previous: "PREVIOUS",
  },
};
