// Edit player-facing copy here. Keep protocol/error identity independent of wording.
export const COPY = {
  errors: {
    name: "Use 1–14 characters.",
    caption: "Use 3–100 characters.",
    settings: "Choose 1–15 rounds and 10–60 seconds.",
    full: "ROOM FULL",
    duplicateName: "NAME ALREADY IN USE",
    nameLocked: "Names can only change in the lobby.",
    color: "Choose a lobby color.",
    kick: "Only the host can remove players in the lobby.",
    settingsHost: "Only the host can change lobby settings.",
    host: "HOST ONLY",
    phase: "PHASE ALREADY CLOSED",
    wait: "Action unavailable in this phase.",
    minimum: "4 PLAYERS REQUIRED",
    images: "Add images before starting.",
    finish: "Finish the game first.",
    alive: "Ending early is unavailable.",
    skip: "No phase to skip.",
    breathe: "Please wait.",
    image: "Image unavailable.",
    pending: "JOINING NEXT ROUND",
    captionClosed: "CAPTION TIME ENDED",
    votingClosed: "VOTING CLOSED",
    selfVote: "You cannot vote for yourself.",
    unknown: "Action unavailable.",
    origin: "Please use this site.",
    large: "Request too large.",
    create: "Could not create room. Try again.",
    session: "SESSION ENDED. Join again.",
    duplicateSession: "SESSION ALREADY OPEN",
    invalid: "Invalid request. Try again.",
    service: "CONNECTION LOST. Try again.",
    setup: "Room service needs setup. See README.",
    notFound: "ROOM NOT FOUND",
    offline: "CONNECTION LOST. Reconnecting…",
    busy: "Room busy. Try again.",
  },
  home: {
    eyebrow: "A MULTIPLAYER CAPTION GAME",
    title1: "MAKE",
    title2: "MEMES.",
    title3: "PLAY WITH",
    title4: "FRIENDS.",
    intro1: "Create a room. Invite your friends.",
    intro2: "Write captions and vote for your favorites.",
    players: "4–12 PLAYERS",
    downloads: "NO DOWNLOADS",
    tag: "PLAY TOGETHER",
    entryTop: "2029 GOOBERS",
    sticker1: "CAPTION",
    sticker2: "& VOTE",
    entry1: "LET’S",
    entry2: "PLAY.",
    name: "YOUR NAME",
    namePlaceholder: "Enter your name",
    nameHint: "Up to 14 characters. Emojis supported.",
    create: "CREATE A ROOM",
    or: "OR JOIN A ROOM",
    code: "ROOM CODE",
    join: "JOIN →",
    note: "Join with a five-character room code.",
    marquee: "WRITE A CAPTION ✳ WATCH THE SLIDESHOW ✳ VOTE FOR YOUR FAVORITE ✳",
    footer1: "A GAME FOR FRIENDS.",
    footer2: "2029 GOOBERS",
  },
  lobby: {
    title: "LOBBY",
    invite: "INVITE YOUR FRIENDS",
    assemble: "MEET THE",
    goobers: "GOOBERS.",
    codeLabel: "ROOM CODE",
    copy: "COPY CODE ↗",
    you: "YOU",
    offline: "OFFLINE",
    online: "CONNECTED",
    needed: "more players needed",
    rename: "RENAME",
    rounds: "ROUNDS",
    timer: "CAPTION TIMER",
    mode: "IMAGE MODE",
    same: "SAME IMAGE",
    different: "DIFFERENT IMAGES",
    start: "START GAME ↗",
    hint: "Click your name to change your name or color.",
    joining: "YOU’RE IN",
    joiningHint: "JOINING NEXT ROUND",
  },
  caption: {
    title: "WRITE A",
    titleAccent: "CAPTION.",
    label: "Your caption",
    placeholder: "Write your caption…",
    update: "UPDATE CAPTION ↗",
    submit: "SUBMIT CAPTION ↗",
    saved: "Submitted. You can edit until captioning closes.",
  },
  round: {
    starting: "GET READY",
    loading: "STARTING GAME",
    intro: "NEW ROUND",
    final: "FINAL",
    round: "ROUND",
    roundEnd: "ROUND",
    seconds: "SECONDS",
  },
  shame: {
    title: "PIN OF SHAME",
    subtitle: "No caption submitted.",
  },
  grave: {
    title: "PLAYER DISCONNECTED",
    subtitle: "Disconnected before submitting.",
  },
  slideshow: {
    exhibit: "MEME",
    anonymous: "ANONYMOUS",
    vote: "TIME TO VOTE",
    next: "NEXT MEME",
    waiting: "Waiting for",
    waitingEnd: "to continue.",
  },
  voting: {
    intro: "ONE VOTE PER PLAYER",
    title: "TIME TO",
    accent: "VOTE.",
    own: "YOUR CAPTION",
    selected: "✓ SELECTED",
    select: "SELECT",
    hint: "Change your vote until voting closes. Missed votes are assigned randomly.",
  },
  results: {
    intro: "VOTING COMPLETE",
    verdict: "VOTE RESULTS",
    empty: "No captions submitted. No points awarded.",
    single: "Only one caption submitted. Automatic winner.",
    tie: "TIED WINNERS",
    winnerIntro: "RESULTS",
    winner: "ROUND WINNER",
    noWinner: "NO WINNER",
    unanimous: "✳ UNANIMOUS +50%",
    authorTitle: "CAPTION AUTHORS",
  },
  leaderboard: {
    intro: "ROUND COMPLETE",
    title: "CURRENT",
    accent: "STANDINGS",
    consolation: "Last place",
    next: "NEXT ROUND",
    final: "FINAL RESULTS",
    waiting: "Waiting for",
  },
  podium: {
    intro: "GAME COMPLETE",
    title: "FINAL",
    accent: "PODIUM",
    tied: "TIED",
    first: "1ST",
    second: "2ND",
    third: "3RD",
  },
  awards: {
    intro: "GAME AWARDS",
    title: "PLAYER",
    accent: "AWARDS",
    best: "🏆 BEST MEME ·",
    pins: "📌 Pin Collector",
    fire: "🔥 On Fire",
    votes: "💖 People Pleaser",
    deaths: "🪦 Gone Too Soon",
    robbed: "😭 Robbed",
    continue: "CONTINUE →",
  },
  end: {
    intro: "GAME OVER",
    title: "PLAY",
    accent: "AGAIN?",
    rematch: "REMATCH ↗",
    lobby: "RETURN TO LOBBY",
    waiting: "Waiting for the host.",
  },
  common: {
    reconnecting: "Reconnecting…",
    lost: "CONNECTION LOST",
    recover: "Trying to reconnect…",
    retry: "RETRY",
    retrySession: "RECONNECT",
    leaveSession: "LEAVE SESSION",
    vanished: "HALF THE PLAYERS DISCONNECTED",
    continue: "CONTINUE GAME",
    end: "END GAME",
    leave: "LEAVE ROOM",
    skip: "SKIP PHASE ↗",
    footer: "2029 GOOBERS",
    fallback: "IMAGE UNAVAILABLE",
    fallbackHint: "You can still submit a caption.",
    helpTitle: "HOW TO PLAY",
    help: "Write a caption, watch the slideshow, then vote for another player’s caption.",
    scoring:
      "Each vote earns 25 points. Every other eligible player’s manual vote earns +50%. Consecutive wins add +10%.",
  },
};
